apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus
  namespace: monitoring

spec:
  chart: kube-prometheus-stack
  targetNamespace: monitoring 
  repo: https://prometheus-community.github.io/helm-charts 